// Генерация PDF-каталога на JavaScript (используя библиотеку jsPDF)
function generateCatalogPDF() {
  // Создаем новый PDF документ
  const doc = new jsPDF();
  
  // Заголовок каталога
  doc.setFontSize(20);
  doc.setTextColor(40, 53, 147);
  doc.text('Golden Pages Library - Book Catalog', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(81, 81, 81);
  doc.text('Current as of ' + new Date().toLocaleDateString(), 105, 30, { align: 'center' });
  
  // Данные книг из каталога
  const books = [
    {
      title: "The Silent Patient",
      author: "Alex Michaelides",
      year: "2019",
      rating: "★★★★☆ (12,345)",
      status: "Available",
      description: "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer..."
    },
    {
      title: "Atomic Habits",
      author: "James Clear",
      year: "2018",
      rating: "★★★★★ (24,789)",
      status: "Bestseller",
      description: "No matter your goals, Atomic Habits offers a proven framework for improving--every day..."
    },
    {
      title: "Educated",
      author: "Tara Westover",
      year: "2018",
      rating: "★★★★☆ (15,632)",
      status: "New Arrival",
      description: "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family..."
    },
    {
      title: "Rich Dad Poor Dad",
      author: "Robert Kiyosaki",
      year: "1997",
      rating: "★★★★☆ (32,456)",
      status: "",
      description: "Rich Dad Poor Dad is Robert's story of growing up with two dads — his real father and the father of his best friend..."
    },
    {
      title: "The Alchemist",
      author: "Paulo Coelho",
      year: "1988",
      rating: "★★★★★ (45,321)",
      status: "Popular",
      description: "The Alchemist follows a young Andalusian shepherd in his journey to the pyramids of Egypt..."
    },
    {
      title: "The Midnight Library",
      author: "Matt Haig",
      year: "2020",
      rating: "★★★★☆ (18,765)",
      status: "",
      description: "Between life and death there is a library, and within that library, the shelves go on forever..."
    }
  ];
  
  // Создаем таблицу с книгами
  let yPosition = 40;
  books.forEach((book, index) => {
    if (yPosition > 260) {
      doc.addPage();
      yPosition = 20;
    }
    
    // Заголовок книги
    doc.setFontSize(14);
    doc.setTextColor(25, 25, 25);
    doc.text(`${index + 1}. ${book.title}`, 15, yPosition);
    
    // Статус книги (если есть)
    if (book.status) {
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.setFillColor(72, 187, 120); // Зеленый цвет для статуса
      doc.roundedRect(160, yPosition - 5, 30, 7, 3, 3, 'F');
      doc.text(book.status, 175, yPosition, { align: 'center' });
    }
    
    // Автор и год
    doc.setFontSize(12);
    doc.setTextColor(81, 81, 81);
    doc.text(`by ${book.author} (${book.year})`, 15, yPosition + 7);
    
    // Рейтинг
    doc.setTextColor(245, 158, 11); // Оранжевый для рейтинга
    doc.text(`Rating: ${book.rating}`, 15, yPosition + 14);
    
    // Описание
    doc.setFontSize(10);
    doc.setTextColor(81, 81, 81);
    const splitDesc = doc.splitTextToSize(book.description, 180);
    doc.text(splitDesc, 15, yPosition + 21);
    
    // Разделитель
    doc.setDrawColor(200, 200, 200);
    doc.line(15, yPosition + 28 + (splitDesc.length * 5), 195, yPosition + 28 + (splitDesc.length * 5));
    
    yPosition += 35 + (splitDesc.length * 5);
  });
  
  // Футер
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by Golden Pages Library - ' + new Date().toLocaleString(), 105, 290, { align: 'center' });
  
  // Сохраняем PDF
  doc.save('GoldenPages_Catalog.pdf');
}

// Добавляем кнопку для генерации PDF
document.getElementById('downloadBtn').addEventListener('click', function() {
  // Загружаем библиотеку jsPDF динамически
  const script = document.createElement('script');
  script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
  script.onload = function() {
    // После загрузки библиотеки вызываем нашу функцию
    generateCatalogPDF();
  };
  document.head.appendChild(script);
});